import os
import json
import hashlib
from web3 import Web3

# Connect to local Hardhat node
WEB3_PROVIDER_URI = os.getenv("WEB3_PROVIDER_URI", "http://127.0.0.1:8545")
w3 = Web3(Web3.HTTPProvider(WEB3_PROVIDER_URI))

CONTRACT_DATA_PATH = os.path.join(os.path.dirname(__file__), "..", "..", "contract_data.json")

contract = None
default_account = None

def init_blockchain():
    global contract, default_account
    if not w3.is_connected():
        print(f"Failed to connect to Ethereum node at {WEB3_PROVIDER_URI}")
        return

    # Use the first account generated by Hardhat
    default_account = w3.eth.accounts[0]
    
    try:
        with open(CONTRACT_DATA_PATH, "r") as f:
            data = json.load(f)
            
        contract = w3.eth.contract(address=data["address"], abi=data["abi"])
        print(f"Successfully loaded EnterpriseAudit contract at {data['address']}")
    except Exception as e:
        print(f"Could not load contract data: {e}")

def record_audit_event(order_id: str, event_type: str, event_details: str, actor: str):
    if not contract or not default_account:
        print("Blockchain not initialized, skipping audit event.")
        return None
        
    try:
        # Create a deterministic hash of the event details
        event_hash = hashlib.sha256(event_details.encode('utf-8')).hexdigest()
        
        # Build transaction
        tx_hash = contract.functions.recordEvent(
            order_id,
            event_type,
            event_hash,
            actor
        ).transact({'from': default_account})
        
        # Wait for receipt
        receipt = w3.eth.wait_for_transaction_receipt(tx_hash)
        print(f"Blockchain audit recorded! Tx Hash: {receipt.transactionHash.hex()}")
        return receipt.transactionHash.hex()
    except Exception as e:
        print(f"Failed to record blockchain audit: {e}")
        return None
