"""add supplier context and vector

Revision ID: beae210a3830
Revises: ce5ffeb002bc
Create Date: 2026-08-16 22:14:12.001007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import pgvector
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'beae210a3830'
down_revision: Union[str, Sequence[str], None] = 'ce5ffeb002bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.create_table('supplier_context',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('supplier_id', sa.String(), nullable=False),
    sa.Column('context_text', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier_context')
    op.execute('DROP EXTENSION IF EXISTS vector;')
    # ### end Alembic commands ###
