import React from 'react';
import { Package, AlertTriangle } from 'lucide-react';
import { useDemo } from '../state/DemoContext';
import { StatusBadge } from '../components/common/StatusBadge';

export const InventoryPage: React.FC = () => {
  const { inventory } = useDemo();

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h2 className="text-xl font-bold text-white flex items-center gap-2">
          <Package className="w-5 h-5 text-emerald-400" /> Inventory Agent Stock Telemetry
        </h2>
        <p className="text-xs text-slate-400">
          Real-time warehouse stock balances, reorder threshold monitoring, and shortage detection
        </p>
      </div>

      {/* Active Reorder Signal Banner */}
      <div className="bg-[#1C160B] border border-amber-500/30 rounded-2xl p-4 flex items-center justify-between shadow-lg text-xs">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-xl bg-amber-500/20 text-amber-400 flex items-center justify-center shrink-0 border border-amber-500/30">
            <AlertTriangle className="w-5 h-5 animate-pulse" />
          </div>
          <div>
            <div className="font-bold text-amber-300 uppercase tracking-wider text-[11px]">
              Active Reorder Signal Generated by Inventory Agent
            </div>
            <div className="text-slate-300">
              Shortage of <strong>78 units</strong> detected for <em>Industrial Water Pump (Model WP-800)</em>. Procurement Agent dispatched.
            </div>
          </div>
        </div>
        <span className="px-3 py-1 bg-amber-500/20 text-amber-300 border border-amber-500/40 rounded-full font-mono text-[11px]">
          SIGNAL DISPATCHED
        </span>
      </div>

      {/* Inventory Grid Table */}
      <div className="bg-[#121929] border border-[#24334D] rounded-2xl overflow-hidden shadow-xl">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs text-slate-300">
            <thead className="bg-[#0B111E] text-slate-400 uppercase text-[10px] font-semibold tracking-wider border-b border-[#24334D]">
              <tr>
                <th className="py-3 px-4">Item ID</th>
                <th className="py-3 px-4">Product Name</th>
                <th className="py-3 px-4">Current Stock</th>
                <th className="py-3 px-4">Reorder Threshold</th>
                <th className="py-3 px-4">Required</th>
                <th className="py-3 px-4">Shortage</th>
                <th className="py-3 px-4">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#1E293B]">
              {inventory.map(item => (
                <tr key={item.id} className="hover:bg-[#182338] transition-colors">
                  <td className="py-3.5 px-4 font-bold text-white font-mono">{item.id}</td>
                  <td className="py-3.5 px-4 font-medium text-slate-200">{item.productName}</td>
                  <td className="py-3.5 px-4 font-mono font-bold text-cyan-400">{item.currentStock}</td>
                  <td className="py-3.5 px-4 font-mono text-slate-400">{item.reorderThreshold}</td>
                  <td className="py-3.5 px-4 font-mono text-slate-300">{item.required}</td>
                  <td className="py-3.5 px-4 font-mono font-bold text-rose-400">
                    {item.shortage > 0 ? `-${item.shortage}` : '0'}
                  </td>
                  <td className="py-3.5 px-4">
                    <StatusBadge status={item.status} />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
